config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'info/index'
  

  resources :contactos
  resources :tutors

   root 'welcome#index'

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base

	validates_format_of :nombre, :with => /\A[a-zA-Z\s]+\z/ , allow_blank: true
	validates :nombre , :presence => {:message => "Campo obligatorio"}
	validates :email , :presence => {:message => "Campo obligatorio"}
	validates :email, email_format: { message: "no es correcto" } , allow_blank: true
	validates :mensaje , :presence => {:message => "Campo obligatorio"}
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base

	validates_format_of :nombre, :with => /\A[a-zA-Z\s]+\z/ , allow_blank: true
	validates :nombre , :presence => {:message => "Campo obligatorio"}
	validates_format_of :apellido, :with => /\A[a-zA-Z\s]+\z/ , allow_blank: true
	validates :apellido , :presence => {:message => "Campo obligatorio"}
	validates :rut, :uniqueness => {:message => "ya ingresado anteriormente"} , allow_blank: true
	validates :rut, :presence => {:message => "Campo obligatorio"}
	validates :rut, :rut => {:message => "no es valido"} , allow_blank: true
	validates :email , :presence => {:message => "Campo obligatorio"}
	validates :email, email_format: { message: "no es correcto" } , allow_blank: true
	validates :asignatura, :presence => {:message => "tiene campo vacio"}
	validates :carrera, :presence => {:message => "tiene campo vacio"}
	validates :celu, length: { is: 9, :message => "Debe tener 9 digitos" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
  before_action :set_contacto, only: [:show, :edit, :update, :destroy]

  # GET /contactos
  # GET /contactos.json
  def index
    @contactos = Contacto.all
  end

  # GET /contactos/1
  # GET /contactos/1.json
  def show
  end

  # GET /contactos/new
  def new
    @contacto = Contacto.new
  end

  # GET /contactos/1/edit
  def edit
  end

  # POST /contactos
  # POST /contactos.json
  def create
    @contacto = Contacto.new(contacto_params)

    respond_to do |format|
      if @contacto.save
        format.html { redirect_to @contacto, notice: 'Contacto was successfully created.' }
        format.json { render :show, status: :created, location: @contacto }
      else
        format.html { render :new }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contactos/1
  # PATCH/PUT /contactos/1.json
  def update
    respond_to do |format|
      if @contacto.update(contacto_params)
        format.html { redirect_to @contacto, notice: 'Contacto was successfully updated.' }
        format.json { render :show, status: :ok, location: @contacto }
      else
        format.html { render :edit }
        format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contactos/1
  # DELETE /contactos/1.json
  def destroy
    @contacto.destroy
    respond_to do |format|
      format.html { redirect_to contactos_url, notice: 'Contacto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contacto
      @contacto = Contacto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contacto_params
      params.require(:contacto).permit(:nombre, :email, :mensaje)
    end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:nombre, :apellido, :rut, :celu, :email, :carrera, :asignatura)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contactos/_form.html.erb
<%= form_for(@contacto) do |f| %>
<body>


  

  


<div class="col-md-4 col-md-offset-4">

            
          <div class="row center">
           <div class = "col-xs-6 col-sm-12"><%=f.text_field :nombre, placeholder: "NOMBRE"%></div>
          </div>
          <div class="row center">
           <div class = "col-xs-6 col-md-12"><%=f.text_field :email, placeholder: "E-MAIL"%></div>
          </div>
          <div class="row center">
           <div class = "col-xs-6 col-md-12"><%=f.text_area :mensaje, placeholder: "MENSAJE"%></div>
          </div>
           <br>
           <br>

  <div class="center row">
            

           <div class = "col-xs-6 col-md-12">
                <%=f.submit "¡ENVIAR EL MENSAJE! " ,class:"btn center-align"%>
           </div>
           
  </div>

  
</form>
<br>
<br>
<div  class="jumbotron ">   
        
          <div class="row center ">
          <p><a style="color:#FFFFFF;" class="btn btn-primary btn-sm"href="https://videotutores.herokuapp.com/" >Volver</a></p>          
              
          </div>       

    </div>




  <% end %>

</body>



  

app/views/contactos/edit.html.erb
<h1>Editing Contacto</h1>

<%= render 'form' %>

<%= link_to 'Show', @contacto %> |
<%= link_to 'Back', contactos_path %>

app/views/contactos/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>

app/views/contactos/new.html.erb
<header>Contáctanos</header>

<%= render 'form' %>

app/views/contactos/show.html.erb
<br>
<br>
<div class=jumbotron>
<div class="row center">
<h3 style="color:#FFFFFF;">Tu duda, consulta u observación ha sido enviado con éxito. Te ayudaremos lo más pronto posible. Gracias por confiar en nosotros !</h3>
<p><a style="color:#FFFFFF;" class="btn btn-primary btn-sm"href="https://videotutores.herokuapp.com/" >Volver</a></p> 
</div>
</div>

app/views/info/index.html.erb
<!DOCTYPE html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>

  	<br>
  	<br>
  	<br>
  		<div class="center-block">
  			<img src='<%= asset_path 'doblado.jpg' %>'  class="img-responsive img-rounded center-block"  width="900" height="400"/>
  		</div>
  	<br>
  	<br>
  <div  class= "row center ">
  		<div class= "container center" style="background-color: #34495e";>
  			<br>
  			<p style="color:#FFFFFF;">De la mano del gobierno de Chile, a través del FDI(Fondo de Desarrollo Institucional),se nos ha otorgado el privilegio de realizar nuestra propuesta llamada "Videotutores", que consiste en centrar el estudio de cientos de estudiantes de primer año de ingeniería de la sede Macul en la universidad UTEM, a través de videos con contenido relevante de pruebas y materia de los ramos más complejos, para ello contaremos con ayudantes capacitados que los guiarán en todo el proceso.</p>
          
        </div>
  </div>

  <br>
  <br>

  <div  class= "row center ">
  		<div class= "container center" style="background-color: #27ae60";>
  			<br>
  			<p style="color:#FFFFFF;">Somos un grupo de estudiantes de la sede Macul, quienes estamos a cargo de coordinar el contenido, edición y ejecución de los videos, en su mayoría validados con profesores. Nuestra única misión es ayudar al estudiante que viene ingresando a la universidad, otorgándoles herramientas de conocimiento. Queremos disminuír la taza de reprobados en los ramos más difíciles, es por ello la iniciativa de incluír a la misma gente dentro de la universidad.</p>
          
        </div>
  </div>
  <br>
  <br>
  

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->

    <div class="navbar-header">
      
      
      <a class="navbar-brand" href="https://videotutores.herokuapp.com">
        <img src='<%= asset_path 'v1.png' %>' width="25" height="25"/>
      </a>
      <a class="navbar-brand" href="https://www.facebook.com/videotutores/?ref=aymt_homepage_panel">
        <img src='<%= asset_path 'face.png' %>' width="25" height="25"/>
      </a>
      <a class="navbar-brand" href="https://www.youtube.com/channel/UCnvz8bO5o8p63ExZnnXe67g">
        <img src='<%= asset_path 'you.png' %>' width="25" height="25"/>
      </a>
    </div>
    



    
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Videotutores</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

		<%= render 'layouts/navbar' %>




	<div class="container">
	<%= yield %>
	</div>
</body>
</html>

app/views/tutors/_form.html.erb
<%= form_for(@tutor) do |f| %>
   

  
<div class="col-md-4 col-md-offset-4">




<form>


  <div class="center row">

      <div class="col-xs-12 col-sm-6 col-md-12">
        <div class="form-group">     
          <div class="field">
              <label for="name">Nombre</label><br>
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              <%=f.text_field :nombre,:maxlength => 25, placeholder: "NOMBRE"%>       
          </div>
        </div>      
      </div>

    <div class="col-xs-12 col-sm-6 col-md-12">
        <div class="form-group">
          <div class="field">
              <label for="name">Apellido</label><br>
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              <%=f.text_field :apellido,:maxlength => 25,placeholder: "APELLIDO"%>       
          </div>
        </div>
      
    </div>

          


  </div>

  <div class="center row">
      <div class="col-xs-12 col-sm-6 col-md-12">
        <div class="form-group">
          <div class="field">
              <label for="name">Rut</label><br>
              <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
              <%=f.text_field :rut,:maxlength => 10, placeholder: "FORMATO: 12345678-9"%>       
          </div>
        </div>
      
      </div>

    <div class="col-xs-12 col-sm-6 col-md-12">
        <div class="form-group">
          <div class="field">
              <label for="name">Celular</label><br>
              <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
              <%=f.text_field :celu,:maxlength => 9,placeholder: "CELULAR 9 DIGITOS"%>       
          </div>
        </div>
      
    </div>
  </div>

  <div class="center row">
    <div class="col-xs-12 col-sm-6 col-md-12">
        <div class="form-group">
          <div class="field">
              <%= f.label :email %><br>
              <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
              <%= f.text_field :email ,placeholder: "CORREO ELECTRONICO"%>
          </div>
        </div>
    </div>
  </div>

  <div class="center row">
      <div class="col-xs-12 col-sm-6 col-md-12">
        <div class="form-group">
          <div class="field">
              <%= f.label :carrera %><br>
              <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
              <%= f.select(:carrera, options_for_select([['Ingeniería Civil Electrónica/Mecánica','Ingeniería Civil Electrónica/Mecánica'],['Ingeniería Informática/Civil en Computación ', 'Ingeniería Informática/Civil en Computación'], ['Ingeniería Industrial/Civil Industrial', 'Ingeniería Industrial/Civil Industrial'],['Ingeniería Química/Química Industrial/Biotecnología','Ingeniería Química/Química Industrial/Biotecnología'], ['Ingeniería en Geomensura/Transporte y Tránsito','Ingeniería en Geomensura/Transporte y Tránsito'],['Otro','Otro']]), {  prompt: 'Seleccione Carrera' }) %>
          </div>
        </div>
      
      </div>
  </div>

  <div class="center row">
    <div class="col-xs-12 col-sm-6 col-md-12">
        <div class="form-group">
          <div class="field">
              <%= f.label :asignatura %><br>
              <span class="glyphicon glyphicon-font" aria-hidden="true"></span>
              <%= f.select(:asignatura, options_for_select([['Algebra I', 'Algebra I'], ['Calculo I', 'Calculo I'],['Química General', 'Química General'], ['Física Clásica', 'Física Clásica'], ['Otro', 'Otro']]), {  prompt: 'Seleccione Asignatura a realizar' }) %>
          </div>
        </div>
    </div>
  </div>

<br>



  <div class="center row">
          <button type="submit" class="btn btn-default btn-lg" style="border-color:#27ae60; border:groove; color:#27ae60;" >
           <div class = "col-xs-12 col-sm-6 col-md-12">
                <span class="glyphicon glyphicon-thumbs-up"> ENVIAR</span>
                
                </button>
           </div>
  </div>


</form>
<br>
<br>

</div>

<br>
<div class="col-md-10 col-md-offset-1">
<div  class="jumbotron">   
        
          <div class="row center ">
          <p><a style="color:#FFFFFF;" class="btn btn-primary btn-sm"href="https://videotutores.herokuapp.com/" >Volver</a></p>             
          </div>  

</div>
</div>



<% end %>

app/views/tutors/edit.html.erb
<h1>Editing Tutor</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutor %> |
<%= link_to 'Back', tutors_path %>

app/views/tutors/index.html.erb
<!DOCTYPE html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  </head>

  <body>

    
    

    <div style="color:#FFFFFF"; class="container center">
      <div class="jumbotron center" style="background-color: #2c3e50";>
        <h2> Inscríbete como Videotutor</h2>
        <img src='<%= asset_path 'mini.jpg' %>' class="img-rounded"   width="210" height="100"/>
        <br>
        <br>
        <p class="lead">Estamos buscando ayudantes o alumnos de la universidad para grabar videos de diversos ramos, para ir en ayuda de estudiantes nuevos. El único requisito es tener disponibilidad para realizar estas grabaciones. En caso que quedes seleccionado, te contactaremos. ¿Estás preparado para inscribirte en este desafío? </p>
        <p><a style="color:#FFFFFF;" class="btn btn-primary btn-lg" href="tutors/new" >Inscribirme</a></p>
        
      </div>
    </div>


 
</html>

app/views/tutors/new.html.erb
<header>Inscríbete</header>
<br>
<br>

<%= render 'form' %>

app/views/tutors/show.html.erb
<br>
<br>
<div class=jumbotron>
<div class="row center">
<h3 style="color:#FFFFFF;"> Se han enviado tus datos, te estaremos comunicando via mail si has quedado seleccionado, muchas gracias por aceptar este desafío!</h3>
<p><a style="color:#FFFFFF;" class="btn btn-primary btn-sm"href="https://videotutores.herokuapp.com/" >Volver</a></p> 
</div>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<head>

    <br>
    <div  class="jumbotron center">   
        <h1 style="color:#f39c12;">VIDEOTUTORES</h1>
        <h3 style="color:#f39c12;">¿Quieres ser parte de este novedoso proyecto?</h3> 
          <br>
          <div class="row center">
           <p><a style="color:#FFFFFF;" class="btn btn-primary btn-lg" href="tutors" >¡QUIERO UNIRME!</a></p>             
              
          </div>       

    </div>
    
    <div class="container" style="color:#2c3e50;" >
    <div  class= "row center ">
        <div class="col-md-6">
          <h1><span class="glyphicon glyphicon-book" aria-hidden="true"></span></h1>
          <h2>Quienes somos</h2>
          <p>Te enseñamos de una manera diferente, intuitiva y eficaz. El mundo actual requiere de personas capaces de trasmitir conocimiento, y nosotros estamos a la vanguardia, para que tengas la mejor experiencia estudiando con nosotros.</p>
          <p><a style="color:#FFFFFF;" class="btn btn-success", <%= link_to "Más información", info_index_path%> </a></p>

        </div>


        <div class="col-md-6">
          <h1><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></h1>
          <h2>¿Necesitas ayuda?</h2>
          <p>Envíanos un mensaje para que podamos resolver tus inquietudes, recuerda que estamos disponibles todos los días del año. Nuestros ayudantes se encargarán de proporcionarte la ayuda que necesitas</p>
           <p><a style="color:#FFFFFF;" class="btn btn-success", <%= link_to "Contactanos", new_contacto_path(@contacto)%> </a></p>
          
        </div>
    </div>
    </div>
     
      
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <footer>
        <p>© 2017 Ariel Vargas.</p>
      </footer>

    
</body>
</html>